userId:
  $ref: parameters/userId.yaml

streamId:
  $ref: parameters/streamId.yaml

user:
  $ref: parameters/user.yaml

limit:
  $ref: parameters/limit.yaml

country:
  $ref: parameters/country.yaml

page:
  $ref: parameters/page.yaml

category:
  $ref: parameters/category.yaml

categoryId:
  $ref: parameters/categoryId.yaml
